\
---
# Lista de paquetes Windows a instalar (extensible)
windows_packages:
  - name: "Nagios NCPA"
    vendor: "Nagios Enterprises"
    summary: "NCPA Agent"
    description: "Instalacion automatizada de NCPA (Nagios) via lote, diferenciando PROD/DRP por grupo en inventario."
    share_path: "\\\\kirov01\\SISTEMASOPERATIVOS_WINDOWSLINUX\\Software\\Agente Nagios\\Nagios"
    dest_dir: "C:\\sys"
    files:
      - "ncpa.exe"
      - "install_prod.bat"
      - "install_drp.bat"
    # Lotes a ejecutar dependiendo del grupo
    batch_prod: "install_prod.bat"
    batch_drp: "install_drp.bat"
    # Servicio y version (opcional)
    service_name: "NCPA"
    version_from_file: "C:\\Program Files\\Nagios\\NCPA\\ncpa.exe"
