---
commands_windows:
  - name: top_cpu_processes
    script: |
      Get-Process | Sort-Object CPU -Descending | Select-Object -First 10 Id,ProcessName,CPU,WS,PM | Format-Table -AutoSize

  - name: top_working_set_processes
    script: |
      Get-Process | Sort-Object WS -Descending | Select-Object -First 10 Id,ProcessName,CPU,WS,PM | Format-Table -AutoSize

  - name: basic_os_info
    script: |
      Get-CimInstance Win32_OperatingSystem | Select-Object Caption,Version,BuildNumber,OSArchitecture,LastBootUpTime | Format-List

  - name: top_services_sample
    script: |
      Get-Service | Sort-Object Status,Name | Select-Object -First 30 Status,Name,DisplayName | Format-Table -AutoSize
